---
title: "Hackathon Dashboard Notebook"
author: "Michael Puerto, Jazarai Sturdivant"
date: "11/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r cars}
#Source: http://rstudio.github.io/shinydashboard/get_started.html
#install.packages("shinydashboard")
library(shiny)
library(shinydashboard)

ui <- dashboardPage(
  
  dashboardHeader(title = "Energy Consumption"),
  dashboardSidebar(),
  dashboardBody(
    #Arranging boxes in rows (or columns)
    fluidRow(
      box(plotOutput("plot1", height = 250)),
      
      box(
        
        title = "Controls",
        sliderInput("slider", "Number of observations:", 1, 100, 50)
      )
      
    )
    
  )
  
)

server <- function(input, output) {
  
  set.seed(122)
  histdata <- rnorm(500)

  output$plot1 <-renderPlot({
    data <- histdata[se1_len(input$slider)]
    hist(data)
    
  })  
  
}

shinyApp(ui, server)

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
